# -*- coding: utf-8 -*-
"""C2_CnC

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQIqC-jIp_7ZEFEtctzLFDDk4u0H7RvN
"""

balance = 5200
back = ('Y')
pin = int(input('Please Enter You 4 Digit Pin: '))

if pin == (123456):
  while back not in ('n','NO','no','N'):
      print('\nPlease choose the transaction to continue:\n')
      print('1) Check Balance\n')
      print('2) Withdraw Cash\n')
      
      option = int(input('Choose the transaction to continue:\n'))
      if option == 1:
        print('Your Account Balance is RM',balance,'\n')
        back = input('Would you like to continue? ')
        if back in ('n','NO','no','N'):
          print('Thank you for using our service \n')
          break
          
      elif option == 2:
        withdraw = float(input('Choose/enter the amount: \n1) RM 100/2) RM 200/3) RM 300/4) RM 400/5) RM 500/6) RM 600 for other amount enter 7: '))
        if withdraw in [1, 2, 3, 4, 5, 6]:
          balance = balance - withdraw
          print ('\nYour current balance: RM ',balance)
          print ('\nPlease take the cash dispensed')
          print ('\nThank you for using our service')
          break

        elif withdraw == 7:
          withdraw = float(input('Please enter amount: RM '))
          if withdraw <= balance:
            balance = balance - withdraw
            print ('\nYour current balance: RM ',balance)
            print ('\nPlease take the cash dispensed')
            print ('\nThank you for using our service')
            break
          elif withdraw >= balance:
            print ('Your transaction has been cancelled/ is unsuccessful due to insufficient balance')
            break

      else:
        print('Please enter a correct number. \n')
        back = ('y')
elif pin != (123456):
  print('Incorrect Pin!')